"""empty message

Revision ID: 3804914c1213
Revises: e1fd4b9bbd46
Create Date: 2022-12-09 07:51:19.328026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3804914c1213'
down_revision = 'e1fd4b9bbd46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(length=50), server_default='1', nullable=True))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(length=50), server_default='1', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('user')

    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_column('user')

    # ### end Alembic commands ###
