"""empty message

Revision ID: 49556c9b0af1
Revises: 
Create Date: 2022-12-12 12:08:52.386659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49556c9b0af1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=50), server_default='asdf@asdf.com', nullable=True))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=50), server_default='asdf@asdf.com', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('user_email')

    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
