"""empty message

Revision ID: 5e21c6dfaeb6
Revises: ae7bb3d811a2
Create Date: 2022-12-13 07:44:31.688621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e21c6dfaeb6'
down_revision = 'ae7bb3d811a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
