"""empty message

Revision ID: 7a952a647edd
Revises: 3804914c1213
Create Date: 2022-12-09 07:51:43.058173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a952a647edd'
down_revision = '3804914c1213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
