"""empty message

Revision ID: ae7bb3d811a2
Revises: 49556c9b0af1
Create Date: 2022-12-12 13:55:53.387915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7bb3d811a2'
down_revision = '49556c9b0af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('user_email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True,
               existing_server_default=sa.text("'asdf@asdf.com'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('user_email',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'asdf@asdf.com'"))

    # ### end Alembic commands ###
