"""empty message

Revision ID: e1fd4b9bbd46
Revises: 64bc6fc0842f
Create Date: 2022-12-07 10:22:18.526376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fd4b9bbd46'
down_revision = '64bc6fc0842f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DateTime(), nullable=False))
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DATETIME(), nullable=False))
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###
